volumes:
  volume-postgres:

networks:
  network-postgres:

services:

  postgres:
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS : --data-checksums
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    networks:
      - network-postgres